news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.news, name="news"),
    path('single-news/<str:pk>/', views.singleNews, name="single-news"),

    path('create-news/', views.createNews, name="create-news"),

    path('update-news/<str:pk>/', views.updateNews, name="update-news"),

    path('delete-news/<str:pk>/', views.deleteNews, name="delete-news"),
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projects, name="projects"),
    path('project/<str:pk>/', views.project, name="project"),

    path('create-project/', views.createProject, name="create-project"),

    path('update-project/<str:pk>/', views.updateProject, name="update-project"),

    path('delete-project/<str:pk>/', views.deleteProject, name="delete-project"),

    
]

vsmChoirApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404


from django.conf import settings 
from django.conf.urls.static import static 

from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('news/', include('news.urls')),
    # path('', TemplateView.as_view(template_name="news.html"), name='news'),
    # path('news', TemplateView.as_view(template_name="news.html"), name='news'),
    path('about_us', TemplateView.as_view(template_name="about_us.html"), name='about_us'),
    path('gallery', TemplateView.as_view(template_name="gallery.html"), name='gallery'),
    path('contact', TemplateView.as_view(template_name="contact.html"), name='contact'),
    path('projects/', include('projects.urls')),
    path('profiles/', include('users.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = views.view_404

projects/models.py
from django.db import models
import uuid
from users.models import Profile
# Create your models here.

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    composer = models.CharField(max_length=200, null=True, blank=True)
    soprano_track = models.FileField(upload_to="songs/", null=True, blank=True, default=None)
    alto_track = models.FileField(upload_to="songs/", null=True, blank=True, default=None)
    tenor_track = models.FileField(upload_to="songs/", null=True, blank=True, default=None)
    bass_track = models.FileField(upload_to="songs/", null=True, blank=True, default=None)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, upload_to ="images/", default="images/default.jpg")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default =uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank = True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default =uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    # def __str__(self):
    #     return self.created

projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Project, Review

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'composer','featured_image','description', 'soprano_track','alto_track','tenor_track','bass_track' ]
        

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})
        # self.fields['title'].widget.attrs.update({'class':'input', 'placeholder':'Add title'})

        # self.fields['description'].widget.attrs.update({'class':'input'})

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['body']

        labels = {
            'body': 'Dodaj komentarz do nagrania'
        }
    
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

projects/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import Project
from .forms import ProjectForm, ReviewForm

@login_required(login_url="login")
def projects(request):

    search_query = ''

    if request.GET.get('search_query'):
        search_query = request.GET.get('search_query')
    
    #projects= Project.objects.filter(title__icontains=search_query)
    projects = Project.objects.filter(Q(title__icontains=search_query) | Q(composer__icontains=search_query))
    context = {'projects':projects, 'search_query':search_query}
    print("search: ", search_query)
    # projects = Project.objects.all()
    # context = {'projects': projects}

    return render(request, 'projects/projects.html', context)

def project(request, pk):
    projectObj = Project.objects.get(id=pk)
    profile = request.user.profile
    print(profile.voice)
    form = ReviewForm()
    
    if request.method == "POST":
        form = ReviewForm(request.POST)
        review = form.save(commit=False)
        review.project = projectObj
        review.owner = request.user.profile
        review.save()

        #Update project votecounter
        messages.success(request, 'Your review was successfully submitted')
        return redirect('project', pk=projectObj.id)

    return render(request, 'projects/single-project.html', {'projectObj': projectObj, 'profile':profile, 'form':form} )

@login_required(login_url="login")
def createProject(request):
    profile = request.user.profile
    form = ProjectForm()

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = profile
            project.save()
            return redirect('projects')

    context = {'form': form}
    return render(request, "projects/project_form.html", context)   

@login_required(login_url="login")
def updateProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    form = ProjectForm(instance=project)

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance = project)
        if form.is_valid():
            form.save()
            return redirect('projects')

    context = {'form': form}
    return render(request, "projects/project_form.html", context)  

@login_required(login_url="login")
def deleteProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    if request.method == "POST":
        project.delete()
        return redirect("projects")
    context = {'object': project}
    return render(request, 'projects/delete_template.html', context) 

projects/templates/projects/delete_template.html
{% extends 'main.html' %}
{% block content %} 

<form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"</p>

    <a href="{% url 'projects' %}">Go Back</a>

    <input type="submit" value="Confirm" />
</form>

{%endblock%}

projects/templates/projects/project_form.html
{% extends 'main.html' %}
{% block content %}


<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" />

            <a class="backButton" href="{% url 'account' %}"><i class="zmdi zmdi-arrow-left"></i></a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{field.label}} </label>
                    {{field}}
                </div>
                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
{% endblock %}

projects/templates/projects/projects.html
{% extends 'main.html' %}
{% block content %}

 <!-- Main Section -->
<main class="projects">
<section class="hero-section text-center">
    <div class="container container--narrow">
    <div class="hero-section__box">
        <h3>Wyszukaj utwór po tytule lub kompozytorze </h3>
    </div>

    <div class="hero-section__search">
        <form class="form" action="#" method="get">
        <div class="form__field">
            
            <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="" value="{{search_query}}" />
        </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Wyszukaj" />
        </form>
    </div>
    </div>
</section>
<!-- Search Result: DevList -->
<section class="projectsList">
    <div class="container">
    <div class="grid grid--three">

        {% for project in projects %}
        <div class="column">
        <div class="card project">
            <a href="{% url 'project' project.id %}" class="project">
            <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" style="width: 25em;" />
            <div class="card__body">
                <h3 class="project-title">{{project.title}}</h3>
                <p><a class="project__author" href="">{{project.composer}}</a></p>
                
                
            </div>
            </a>
        </div>
        </div>
        {% endfor %}

    </div>
    </div>
</section>


</main>

{% endblock content %}

projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% block content %}


<!-- Main Section -->
<main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          
          <img class="singleProject__preview" src="{{ projectObj.featured_image.url }}" alt="portfolio thumbnail" />

          {% if projectObj.source_link %}
            <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Source Code </a>
          {% endif %}
                 
        </div>
        <div class="column column--2of3">
          <a href="profile.html" class="singleProject__developer">{{project.owner.name}}</a>
          <h2 class="singleProject__title" style='margin-bottom: 1rem;'>{{projectObj.title}}</h2>
          <h3 class="singleProject__subtitle" style='margin-bottom: 3rem;'>{{projectObj.composer}}</h3>
          
          {% if profile.voice == "Sopran" %}
            {% if projectObj.soprano_track.url != 'None' %}
            <h4>{{profile.voice}}</h4>
            <audio controls>
              <source src="{{projectObj.soprano_track.url}}" type="audio/mpeg">
            Your browser does not support the audio element.
            </audio>
            {% else %}
            <a>Brak nagrania!</a>
            {% endif %}

          {% elif profile.voice == "Alt" %}
          {% if projectObj.alto_track.url != 'None' %}
            <h4>{{profile.voice}}</h4>
            <audio controls>
              <source src="{{projectObj.alto_track.url}}" type="audio/mpeg">
            Your browser does not support the audio element.
            </audio>
            {% else %}
            <a>Brak nagrania!</a>
            {% endif %}

          {% elif profile.voice == "Tenor" %}
          {% if projectObj.tenor_track.url != 'None' %}
            <h4>{{profile.voice}}</h4>
            <audio controls>
              <source src="{{projectObj.tenor_track.url}}" type="audio/mpeg">
            Your browser does not support the audio element.
            </audio>
            {% else %}
            <a>Brak nagrania!</a>
            {% endif %}

          {% elif profile.voice == "Bas" %}
          {% if projectObj.bass_track.url != 'None' %}
            <h4>{{profile.voice}}</h4>
            <audio controls>
              <source src="{{projectObj.bass_track.url}}" type="audio/mpeg">
            Your browser does not support the audio element.
            </audio>
            {% else %}
            <a>Brak nagrania!</a>
            {% endif %}

          {% else %}
          <a href="{% url 'edit-account' %}">W ustawieniach konta wybierz głos, w którym śpiewasz</a>
          {% endif %}
        
          
          <div class="comments">
            

            
            <form class="form" action="{% url 'project' projectObj.id %}" method="POST">
              {% csrf_token %}
              {% for field in form %} 
              <div class="form__field">
                <label for="formInput#textarea">{{field.label}} </label>
                {{field}}
              </div>
              {% endfor %}

              <input class="btn btn--sub btn--lg" type="submit" value="Prześlij komentarz" />
            </form>
            <div class="commentList">
              
              {% for review in projectObj.review_set.all %}
              <div class="comment">
                <a href="{% url 'user-profile' review.owner.id %}">
                  <img class="avatar avatar--md" src="{{review.owner.profile_image.url}}" alt="user" />
                </a>

                <div class="comment__details">
                  <a href="{% url 'user-profile' review.owner.id %}" class="comment__author">{{review.owner.name}}</a>
                  <p class="comment__info">{{review.body|linebreaksbr}}</p>
                </div>
              </div>
              {% endfor %} 

            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>

{% endblock content %}